// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDehLE7vr2357ZBa71D1TUECCY4CU4BX3o',
    appId: '1:716390599022:web:bf7288f3ba270562ea197f',
    messagingSenderId: '716390599022',
    projectId: 'guild-f42e3',
    authDomain: 'guild-f42e3.firebaseapp.com',
    storageBucket: 'guild-f42e3.firebasestorage.app',
    measurementId: 'G-S4LYLYFNVC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT44UK8DW06FfsPSuhzNLzc11hx6OQNOM',
    appId: '1:716390599022:android:9066975c645f71a8ea197f',
    messagingSenderId: '716390599022',
    projectId: 'guild-f42e3',
    storageBucket: 'guild-f42e3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2FF4TIe6ITvqDHHyrO-K4LJrEm-T22dQ',
    appId: '1:716390599022:ios:d1a75d954fb4afbcea197f',
    messagingSenderId: '716390599022',
    projectId: 'guild-f42e3',
    storageBucket: 'guild-f42e3.firebasestorage.app',
    iosBundleId: 'com.rodrigguild.guild',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2FF4TIe6ITvqDHHyrO-K4LJrEm-T22dQ',
    appId: '1:716390599022:ios:d1a75d954fb4afbcea197f',
    messagingSenderId: '716390599022',
    projectId: 'guild-f42e3',
    storageBucket: 'guild-f42e3.firebasestorage.app',
    iosBundleId: 'com.rodrigguild.guild',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDehLE7vr2357ZBa71D1TUECCY4CU4BX3o',
    appId: '1:716390599022:web:7a6d9aa01eb46216ea197f',
    messagingSenderId: '716390599022',
    projectId: 'guild-f42e3',
    authDomain: 'guild-f42e3.firebaseapp.com',
    storageBucket: 'guild-f42e3.firebasestorage.app',
    measurementId: 'G-Q4WD3GH2PX',
  );
}
